pipeline {
    agent any

    stages {

        stage('Deploy Container') {
            steps {
                bat 'docker stop inventory-service || exit 0'
                bat 'docker rm inventory-service || exit 0'
                bat 'docker run -d -p 8080:8080 --name inventory-service inventory-service'
            }
        }
    }
}
